Fix vendoring for test module for Bazel 7 (#2857)
If the latest Bazel version in the matrix is 7.x, vendoring for a test
module will fail since the `+` char is expected in the repo names:
```
* Moving vendored module source to /var/lib/buildkite-agent/builds/bk-docker-p7b3/bazel-org-repo-root/module_src
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/buildkite-agent/builds/bk-docker-p7b3/bazel-org-repo-root/.temp_anonymous_module/vendor_src/rules_nixpkgs_core+' -> '/var/lib/buildkite-agent/builds/bk-docker-p7b3/bazel-org-repo-root/module_src'
```

Enable the relevant flag for this major version.